In [1]:
import utils
import main

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import random


In [ ]:
# train_data, train_label, val_data, val_label = utils.load_mnist_trainval()
# test_data, test_label = utils.load_mnist_test()

A - input layer
Z - not active middle later
b - add bias term
then apply an activation function
activation function by tanh or sigmoid, now its not linear
    can be more complex or powreful
using relu, which is like an elbow
Z2, unactivated secon layer is second weight parameter, between first and second layteers, times activiated irst layer, plus bias
    now we apply softmax activation function
e to a single node is  apart of a whole

forward prop, put in stuff an predict image

back prop
how much did prediction deviate rom the actual label and adjust accordingly
dz2 is loss of second later
db2 as average of absolute error
taking error from second layer and applying weigts in reverse to first
need to undo activation to get error from firt layer

then update parameters accordingly
alpha as a hyper-parameter


In [ ]:
# nptrain = np.array(train_data)
# nptrain = nptrain.T
# nptrain_label = np.array(train_label)

# nptest = np.array(test_data).T
# nptest_label = np.array(test_label)

In [ ]:
# n, m = nptrain.shape

In [ ]:
# def init_params():
#     W1 = np.random.rand(10, 784) - 0.5
#     b1 = np.random.rand(10, 1) - 0.5
#     W2 = np.random.rand(10, 10) - 0.5
#     b2 = np.random.rand(10, 1) - 0.5
#     return W1, b1, W2, b2

# def ReLU(Z):
#     return np.maximum(Z, 0)

# def softmax(Z):
#     A = np.exp(Z) / sum(np.exp(Z))
#     return A

# def forward_prop(W1, b1, W2, b2, X):
#     Z1 = W1.dot(X) + b1
#     A1 = ReLU(Z1)
#     Z2 = W2.dot(A1) + b2
#     A2 = softmax(Z2)
#     return Z1, A1, Z2, A2

# def deriv_ReLU(Z):
#     return Z > 0

# def one_hot(Y):
#     one_hot_Y = np.zeros((Y.size, Y.max() + 1))
#     one_hot_Y[np.arange(Y.size), Y] = 1
#     one_hot_Y = one_hot_Y.T
#     return one_hot_Y

# def back_prop(Z1, A1, Z2, A2, W2, X, Y):
#     one_hot_Y = one_hot(Y)
#     dZ2 = A2 - one_hot(Y)
#     dW2 = 1/m * dZ2.dot(A1.T)
#     db2 = 1/m * np.sum(dZ2)
#     dZ1 = W2.T.dot(dZ2)  * deriv_ReLU(Z1)
    
#     dW1 = 1/m * dZ1.dot(X.T)
#     db1 = 1/m * np.sum(dZ1)
    
#     return dW1, db1, dW2, db2

# def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
#     W1 -= alpha * dW1
#     b1 -= alpha * db1
#     W2 -= alpha * dW2
#     b2 -= alpha * db2
#     return W1, b1, W2, b2

# initialize parameters
# subtract .5 so we have values between  0.5 - 0.5

def init_params():
    W1 = np.random.randn(10,n) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    W2 = np.random.randn(10,10) - 0.5
    b2 = np.random.rand(10,10) - 0.5 
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)
    
def deriv_ReLU(Z):
    return Z>0
    
def softmax(Z):
    return (np.exp(Z) / sum(np.exp(Z)))

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    print(W2.shape, A1.shape)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2
    
def one_hot(Y):
    # assumes that are classes 0-9, and we want 10 classes, so 9+1
    # index through one_hot_y to make a range, and Y is all the labels
    # for each row, go to the column specified by the label in Y and set it to 1
    one_hot_Y = np.zeroes((Y.size, Y.max()+1))
    one_hot_Y[np.arnage(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y
    
def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot(Y)
    dW2 = 1/m * dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2)  * deriv_ReLU(Z1)
    
    dW1 = 1/m * dZ1.dot(X.T)
    db1 = 1/m * np.sum(dZ1)
    
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 -= alpha * dW1
    b1 -= alpha * db1
    W2 -= alpha * dW2
    b2 -= alpha * db2
    return W1, b1, W2, b2

In [ ]:
# def get_predictions(A2):
#     return np.argmax(A2, 0)

# def get_accuracy(predictions, Y):
#     print(predictions, Y)
#     return np.sum(predictions == Y) / Y.size

# def gradient_descent(X, Y, alpha, iterations):
#     W1, b1, W2, b2 = init_params()
#     for i in range(iterations):
#         Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
#         dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
#         W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
#         if (i % 10 == 0):
#             print("Iteraction: ", i)
#             print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
#     return W1, b1, W2, b2


def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if (i % 10 == 0):
            print("Iteraction: ", i)
            print("Accuracy: ", get_accuracy(get_predications(A2), Y))
    return W1, b1, W2, b2

In [ ]:
# W1, b1, W2, b2 = gradient_descent(nptrain, nptrain_label, .1, 500)

## SOFTMAX TESTING

In [2]:
train_data, train_label, val_data, val_label = utils.load_mnist_trainval()
data, label = utils.load_mnist_test()
batched_data, batched_label = utils.generate_batched_data(data, label, batch_size=32, shuffle=False, seed=22)

Loading training data...
Training data loaded with 60000 images
Loading testing data...
Testing data loaded with 10000 images
i=0
i=32
i=64
i=96
i=128
i=160
i=192
i=224
i=256
i=288
i=320
i=352
i=384
i=416
i=448
i=480
i=512
i=544
i=576
i=608
i=640
i=672
i=704
i=736
i=768
i=800
i=832
i=864
i=896
i=928
i=960
i=992
i=1024
i=1056
i=1088
i=1120
i=1152
i=1184
i=1216
i=1248
i=1280
i=1312
i=1344
i=1376
i=1408
i=1440
i=1472
i=1504
i=1536
i=1568
i=1600
i=1632
i=1664
i=1696
i=1728
i=1760
i=1792
i=1824
i=1856
i=1888
i=1920
i=1952
i=1984
i=2016
i=2048
i=2080
i=2112
i=2144
i=2176
i=2208
i=2240
i=2272
i=2304
i=2336
i=2368
i=2400
i=2432
i=2464
i=2496
i=2528
i=2560
i=2592
i=2624
i=2656
i=2688
i=2720
i=2752
i=2784
i=2816
i=2848
i=2880
i=2912
i=2944
i=2976
i=3008
i=3040
i=3072
i=3104
i=3136
i=3168
i=3200
i=3232
i=3264
i=3296
i=3328
i=3360
i=3392
i=3424
i=3456
i=3488
i=3520
i=3552
i=3584
i=3616
i=3648
i=3680
i=3712
i=3744
i=3776
i=3808
i=3840
i=3872
i=3904
i=3936
i=3968
i=4000
i=4032
i=4064
i=4096
i=4128
i

In [17]:
x = np.array([[-1.48839468, -0.31530738],
                      [-0.28271176, -1.00780433],
                      [0.66435418, 1.2537461],
                      [-1.64829182, 0.90223236]])
y = np.array([[0.23629739, 0.76370261],
              [0.67372745, 0.32627255],
              [0.35677439, 0.64322561],
              [0.07239128, 0.92760872]])

In [25]:
out = np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)
out

array([[0.23629739, 0.76370261],
       [0.67372745, 0.32627255],
       [0.35677439, 0.64322561],
       [0.07239128, 0.92760872]])

In [26]:
y-out

array([[-3.71937262e-09,  3.71937248e-09],
       [ 1.59436375e-09, -1.59436364e-09],
       [ 1.74628878e-09, -1.74628878e-09],
       [ 1.62559298e-09, -1.62559288e-09]])

## SIG AND DERIVSIG TEST

In [27]:
A = np.array([[-1.48839468, -0.31530738],
              [-0.28271176, -1.00780433],
              [0.66435418, 1.2537461],
              [-1.64829182, 0.90223236]])
B = np.array([[0.1841628, 0.4218198],
              [0.42978908, 0.26740977],
              [0.66023782, 0.77794766],
              [0.16133995, 0.71140804]])

In [29]:
sig = 1 / (1+np.exp(-A))

In [34]:
 np.sum(np.abs((sig - B)))

2.0660873317757122e-08

In [36]:
C = np.array([[-1.48839468, -0.31530738],
              [-0.28271176, -1.00780433],
              [0.66435418, 1.2537461],
              [-1.64829182, 0.90223236]])
D = np.array([[0.15024686, 0.24388786],
              [0.24507043, 0.19590178],
              [0.22432384, 0.1727451],
              [0.13530937, 0.20530664]])

In [38]:
sigd = 1 / (1+np.exp(-C))
outD = sigd * (1-sigd)
outD

array([[0.15024686, 0.24388786],
       [0.24507043, 0.19590178],
       [0.22432384, 0.1727451 ],
       [0.13530937, 0.20530664]])

In [41]:
sum(np.abs(D-outD))

array([9.28886890e-09, 9.90633417e-09])

## TEST RELU and DERIV

In [43]:
E = np.array([[-1.48839468, -0.31530738],
              [-0.28271176, -1.00780433],
              [0.66435418, 1.2537461],
              [-1.64829182, 0.90223236]])
F = np.array([[0.0, 0.0],
              [0.0, 0.0],
              [0.66435418, 1.2537461],
              [0.0, 0.90223236]])

In [44]:
sum(np.abs(F - np.maximum(E, 0)))

array([0., 0.])

In [46]:
G = np.array([[-1.48839468, -0.31530738],
              [-0.28271176, -1.00780433],
              [0.66435418, 1.2537461],
              [-1.64829182, 0.90223236]])
H = np.array([[0.0, 0.0],
              [0.0, 0.0],
              [1., 1.],
              [0.0, 1.]])

In [55]:
(G>0).astype(float) == H

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

## TEST CROSS ENTROPY

In [92]:
x = np.array([[0.2, 0.5, 0.3], [0.5, 0.1, 0.4], [0.3, 0.3, 0.4]])
y = np.array([1, 2, 0])
expected_loss = 0.937803


In [130]:
log_loss = np.log(x)
y_values = np.arange(len(y)),y
expected_loss -np.mean(-log_loss[y_values])

-5.722533453766943e-07

In [133]:
log_loss[y_values]

array([-0.69314718, -0.91629073, -1.2039728 ])

## TEST ACCURACY

In [128]:
x = np.array([[0.2, 0.5, 0.3], [0.5, 0.1, 0.4], [0.3, 0.3, 0.4]])
y = np.array([1, 2, 0])
y_values = x[np.arange(len(y)),y]
expected_acc = 0.3333
y_values

array([0.5, 0.4, 0.3])

In [150]:
#acc = sum(x.max(axis=1) == x[y_values]) / y.size
x[y_values]

array([0.5, 0.4, 0.3])

In [ ]:
train_data, train_label, val_data, val_label = utils.load_mnist_trainval()
data, label = utils.load_mnist_test()
batched_data, batched_label = utils.generate_batched_data(data, label, batch_size=32, shuffle=False, seed=22)

## softmax regression

In [159]:
def __init__(self, input_size=28 * 28, num_classes=10):
    """
    A single layer softmax regression. The network is composed by:
    a linear layer without bias => (activation) => Softmax
    :param input_size: the input dimension
    :param num_classes: the number of classes in total
    """
    super().__init__(input_size, num_classes)
    self._weight_init()

def _weight_init(self):
    '''
    initialize weights of the single layer regression network. No bias term included.
    :return: None; self.weights is filled based on method
    - W1: The weight matrix of the linear layer of shape (num_features, hidden_size)
    '''
    np.random.seed(1024)
    self.weights['W1'] = 0.001 * np.random.randn(self.input_size, self.num_classes)
    self.gradients['W1'] = np.zeros((self.input_size, self.num_classes))

ModuleNotFoundError: No module named 'softmax_regression'